### ISSUE TITLE
easily modifiable command prefixes

### ISSUE THREAD

**Issue by skylar32** [Ispira/Ispyra#1]
At the moment, command prefixes must be edited both in [line 10 of ispyra.py](https://github.com/Ispira/Ispyra/blob/master/Ispyra/ispyra.py#L10) as well as in each instance of the command prefix in the appropriate extension file.  Consider streamlining this so that the command prefix can be modified in a single location, and potentially create a command that makes this variable modifiable through discord.

**Comment by Ispira** [comment]
Per-command prefixes have been removed. Prefixes are now global.
